### PR TITLE
JPL Patch 001. Refactored: 100 lines app.

### PR DESCRIPTION
**Pull request by JeanPaulLucien**
It's about 100 lines app.
I did not test.

### CODE REVIEW

**Comment by alex-free** [comment]
> It's about 100 lines app.
> I did not test.

Hello, this was one of the first programs I ever wrote. I will test your changes, I have longed to do an update to this.

**Comment by alex-free** [comment]
These changes break the program. The first issue I saw is that gen_year will output invalid spec years for the OEM key.

I did find this https://github.com/MobCat/Windows-95-Product-Key-Check which seems okish to verify without setting up a win95 vm. Still real VM is ideal to verify any changes in. 

I will update this eventually...

**Comment by JeanPaulLucien** [comment]
@alex-free show me difference.

**Comment by alex-free** [comment]
> @alex-free show me difference.

Left side is your  fork, right side is v1.0. As you can see, the year digits are always valid in mine but yours sometimes go to 07 (2007!). I also see no difference in the last commit, you just changed digit to i? That seems less readable.

First 3 digits in OEM is the day out of 365, second 2 are the year between 95 and 02 . It can't be anything else. Some subtle bug in your fork is allowing that to not be the case though,

Screenshot_20230213_023336

**Comment by alex-free** [comment]
I think the issue is your code changes just misses too many edge cases. It doesn't really make sense to do it like that IMO, it seems harder to cover every edge case in the while loop.

i did refactor this a different way, it **appears** to work the same but I need to do some more tests:

[o95kg.zip](https://github.com/alex-free/open95keygen/files/10726184/o95kg.zip)

Seems better and is indeed less lines. I think this is the better way to do it.

**Comment by alex-free** [comment]
Going to close this, I updated to v1.0.1 with some optimizations.

**Comment by JeanPaulLucien** [comment]
@alex-free
Thank you. I have fixed year.

**Comment by alex-free** [comment]
> @alex-free Thank you. I have fixed year.

Thanks, releasing v1.0.2 now and your credited!

**Pull request closed without merging**
